#!/bin/bash

(
  cd /home/system/System
  exec java -cp ".:libForVert.x/*" serverStarter/ServerInitializer
) & (
  cd /home/system/System
  source ~/.bash_profile
  exec vertx run webListener/WebListener.java > /dev/null
)
